audios/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name = "audios"

urlpatterns = [
    path("", views.AudiosListView.as_view(), name='inicio')
]

custom_auth/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = "custom_auth"

urlpatterns = [
    path('login', views.LoginView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name="logout"), # https://docs.djangoproject.com/en/5.2/topics/auth/default/#using-the-views
    path('register', views.RegisterView.as_view(), name="register"),
    path('dashboard', views.DashboardView.as_view(), name="dashboard"),
    path('profile/edit', views.EditProfile.as_view(), name="profile_edit"),

] 

proyecto_latam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(settings.ADMIN_SITE_URL, admin.site.urls),
    path('', include('audios.urls', namespace="audios")),
    path('auth/', include('custom_auth.urls', namespace="custom_auth")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/button.html
<button class="cursor-pointer px-3 py-1.5 rounded-md bg-purple-500 text-white font-semibold text-lg hover:scale-110 transition-transform duration-200">{{text}}</button>

templates/partials/mobile_navbar.html
{% url 'audios:inicio' as home_path %}
{% url 'custom_auth:login' as login_path %}
{% url 'custom_auth:register' as register_path %}
{% url 'custom_auth:dashboard' as profile_path %}

<div class="md:hidden  fixed z-20 bottom-0 left-0 w-full border-t bg-purple-800 shadow text-white ">
    <nav >
        <ul class="flex gap-2 w-full">
            <li class="flex-grow transition-colors bg-transparent hover:bg-white/10 ">
                <a class="flex flex-col items-center py-2 text-gray-500 {% if request.path == home_path %}text-white{% endif %}" 
                    href="{{home_path}}">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m2.25 12 8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
                    </svg>
                    <span class="text-sm">Inicio</span>
                </a>
            </li>
       
            {% if request.user.is_authenticated %}
            <li class="flex-grow transition-colors bg-transparent hover:bg-white/10 ">
                <a class="flex flex-col items-center py-2 text-gray-500 {% if request.path == profile_path %}text-white{% endif %} " 
                    href="{{profile_path}}">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                    </svg>
                    <span class="text-sm">Perfil</span>
                </a>
            </li>
            {% else %}
            <li class="flex-grow transition-colors bg-transparent hover:bg-white/10">
                <a class="flex flex-col items-center py-2 text-gray-500 {% if request.path == register_path  %}text-white{% endif %} " 
                    href="{{register_path}}">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
                    </svg>

                    <span class="text-sm">Registrar</span>
                </a>
            </li>

            <li class="flex-grow transition-colors bg-transparent hover:bg-white/10">
                <a class="flex flex-col items-center py-2 text-gray-500 {% if request.path == login_path %}text-white{% endif %} " 
                    href="{{ login_path}}">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 9V5.25A2.25 2.25 0 0 1 10.5 3h6a2.25 2.25 0 0 1 2.25 2.25v13.5A2.25 2.25 0 0 1 16.5 21h-6a2.25 2.25 0 0 1-2.25-2.25V15M12 9l3 3m0 0-3 3m3-3H2.25" />
                    </svg>
                    <span class="text-sm">Entrar</span>
                </a>
            </li>

            {% endif %}
            <li class="flex-grow bg-cyan-400 text-gray-900 border-2 border border-solid border-gray-900">
                <a class="flex flex-col items-center py-2" 
                    href="https://wa.me/556592823891?text=Hola%2C%20est%C3%A1%20interesante%20tu%20sitio." 
                    target="_blank">
                    <svg class="size-6" width="19" height="19" viewBox="0 0 19 19" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path  d="M16.1542 2.76094C14.3772 0.979687 12.0107 0 9.49576 0C4.30469 0 0.0805804 4.22411 0.0805804 9.41518C0.0805804 11.0734 0.51317 12.6935 1.33594 14.1228L0 19L4.99174 17.6895C6.36585 18.4402 7.91384 18.8346 9.49152 18.8346H9.49576C14.6826 18.8346 19 14.6105 19 9.41942C19 6.90446 17.9312 4.54219 16.1542 2.76094ZM9.49576 17.2484C8.08772 17.2484 6.70937 16.871 5.50915 16.1585L5.225 15.9888L2.26473 16.765L3.05357 13.8768L2.86696 13.5799C2.08237 12.333 1.67098 10.8953 1.67098 9.41518C1.67098 5.10201 5.18259 1.5904 9.5 1.5904C11.5908 1.5904 13.5545 2.40469 15.0304 3.88482C16.5062 5.36496 17.4138 7.32857 17.4096 9.41942C17.4096 13.7368 13.8089 17.2484 9.49576 17.2484ZM13.7877 11.3873C13.5545 11.2685 12.3967 10.7002 12.1804 10.6239C11.9641 10.5433 11.8071 10.5051 11.6502 10.7426C11.4933 10.9801 11.0438 11.506 10.9038 11.6672C10.7681 11.8241 10.6281 11.8453 10.3949 11.7266C9.01228 11.0353 8.10469 10.4924 7.19286 8.92745C6.95112 8.51183 7.4346 8.54152 7.88415 7.64241C7.96049 7.48549 7.92232 7.34978 7.86295 7.23103C7.80357 7.11228 7.33281 5.95446 7.13772 5.48371C6.94688 5.02567 6.75179 5.08929 6.60759 5.0808C6.47188 5.07232 6.31496 5.07232 6.15804 5.07232C6.00112 5.07232 5.74665 5.1317 5.53036 5.36495C5.31406 5.60246 4.70759 6.17076 4.70759 7.32857C4.70759 8.48638 5.55156 9.60603 5.66607 9.76295C5.78482 9.91987 7.32433 12.2949 9.68661 13.317C11.1795 13.9616 11.7647 14.0167 12.5112 13.9065C12.965 13.8386 13.9022 13.3382 14.0973 12.7868C14.2924 12.2355 14.2924 11.7647 14.233 11.6672C14.1779 11.5612 14.021 11.5018 13.7877 11.3873Z" fill="currentColor"></path>
                    </svg>
                    <span class="text-xs mt-1">Contacto</span>
                </a>
            </li>
            
        </ul>

    </nav>
</div>

templates/partials/navbar.html
{% load static %}

{% url 'audios:inicio' as home_path %}
{% url 'custom_auth:login' as login_path %}
{% url 'custom_auth:register' as register_path %}
{% url 'custom_auth:dashboard' as profile_path %}

<script>
  /* script para abrir y cerrar el popover de la cuenta del usuario */
  document.addEventListener('DOMContentLoaded', function() {
    const userMenuButton = document.getElementById('user-menu-button');
    if (!userMenuButton) return; // El usuario no se ha logeado

    const userMenu = document.getElementById('user-menu'); // Asumiendo que el menú es el siguiente hermano
    let isMenuOpen = false; // Estado inicial del menú

    userMenuButton.addEventListener('click', function() {
        isMenuOpen = !isMenuOpen; // Toggle el estado

        if (isMenuOpen) {
            userMenu.classList.remove('hidden'); 
            userMenu.classList.add('block'); 
            userMenuButton.setAttribute('aria-expanded', 'true');
        } else {
            userMenu.classList.remove('block'); 
            userMenu.classList.add('hidden'); 
            userMenuButton.setAttribute('aria-expanded', 'false');
        }
    });

    // cerrar popover al hacer click en cualquier otro lugar
    document.addEventListener('click', function(event) {
        if (isMenuOpen && !userMenuButton.contains(event.target) && !userMenu.contains(event.target)) {
            isMenuOpen = false;
            userMenu.classList.remove('block');
            userMenu.classList.add('hidden');
            userMenuButton.setAttribute('aria-expanded', 'false');
        }
    });
});
</script>

<nav class="bg-purple-900 z-20 relative hidden md:block w-full">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
 
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex shrink-0 items-center">
          <img class="h-10 w-auto" src="{% static 'icons/apple-touch-icon.png' %}" alt="Your Company">
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 ", Default: "text-gray-300 hover:bg-cyan-700 hover:" -->
            <a href="{{home_path}}" class="text-white rounded-md {% if request.path == home_path %}bg-cyan-900 {% else %}hover:bg-cyan-700 {% endif %} px-3 py-2 text-sm font-medium" 
                aria-current="page">Inicio</a>

            {% if request.user.is_authenticated %}
            <a href="{{profile_path}}" class="text-white rounded-md {% if request.path == profile_path %}bg-cyan-900 {% else %}hover:bg-cyan-700 {% endif %} px-3 py-2 text-sm font-medium">Perfil</a>
            {% else %}
            <a href="{{login_path}}" class="text-white rounded-md {% if request.path == login_path %}bg-cyan-900 {% else %}hover:bg-cyan-700 {% endif %} px-3 py-2 text-sm font-medium">Iniciar Sesion</a>
            <a href="{{register_path}}" class="text-white rounded-md {% if request.path == register_path %}bg-cyan-900 {% else %}hover:bg-cyan-700 {% endif %} px-3 py-2 text-sm font-medium">Crear Cuenta</a>
            {% endif %}
          </div>
        </div>
      </div>

      {% if request.user.is_authenticated %}
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        
        <!-- Profile dropdown -->
        <div class="relative ml-3">
          <div>
            <button type="button" class="relative flex rounded-full bg-gray-800 text-sm focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800 focus:outline-hidden" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
              <span class="absolute -inset-1.5"></span>
              <span class="sr-only">Open user menu</span>
              <img class="size-8 rounded-full" src="{{request.user.profile_image}}" alt="Imagen de Perfil">
            </button>
          </div>

          <!--
            Dropdown menu, show/hide based on menu state.

            Entering: "transition ease-out duration-100"
              From: "transform opacity-0 scale-95"
              To: "transform opacity-100 scale-100"
            Leaving: "transition ease-in duration-75"
              From: "transform opacity-100 scale-100"
              To: "transform opacity-0 scale-95"
          -->
          <div id="user-menu" class="hidden absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black/5 focus:outline-hidden" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
            <!-- Active: "bg-gray-100 outline-hidden", Not Active: "" -->
            <a href="{{profile_path}}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-black/10 " role="menuitem" tabindex="-1" id="user-menu-item-0">Ver Perfil</a>
            <form action="{% url 'custom_auth:logout' %}" method="post" class="block text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-1">
              {% csrf_token %}
              <button class="w-full px-4 py-2 text-start cursor-pointer hover:bg-black/10 ">Salir</button>
            </form>
          </div>
        </div>
      </div>
      {% endif %}

    </div>
  </div>
 
</nav>